# Generated by Django 5.0.3 on 2024-03-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verifield',
            new_name='verified',
        ),
    ]
