# Generated by Django 5.0.3 on 2024-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_rename_following_profile_followings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('In love', 'In love')], default='single', max_length=100),
        ),
    ]
