# Generated by Django 5.0.3 on 2024-03-20 12:08

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_likes_group_grouppost_page_pagepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Friend'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Friend Request'},
        ),
        migrations.AlterModelOptions(
            name='grouppost',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Group Post'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Notification'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Page'},
        ),
        migrations.AlterModelOptions(
            name='pagepost',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Group Post'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Reply Comment'},
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000000000)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Message',
                'ordering': ['-date'],
            },
        ),
    ]
