# Generated by Django 5.0.3 on 2024-03-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_options_alter_friend_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagepost',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Page Post'},
        ),
    ]
