# Generated by Django 5.0.3 on 2024-03-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_groupchat_groupchatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='memebers',
            new_name='members',
        ),
    ]
