# Generated by Django 5.0.3 on 2024-03-29 10:38

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_memebers_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='noimage.gif', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
