# Generated by Django 5.0.3 on 2024-04-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
