# Generated by Django 5.0.3 on 2024-04-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_grouppostcomment_replygrouppostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grouppost'),
        ),
        migrations.AlterField(
            model_name='replygrouppostcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grouppostcomment'),
        ),
    ]
