# Generated by Django 5.0.3 on 2024-04-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_grouppostcomment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_comments', to='core.grouppost'),
        ),
    ]
